# Generated by Django 5.1.7 on 2025-03-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[("scheduled", "Scheduled"), ("api", "API")],
                        max_length=10,
                    ),
                ),
                ("schedule_time", models.DateTimeField(blank=True, null=True)),
                ("interval", models.IntegerField(blank=True, null=True)),
                ("api_payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
