# Generated by Django 5.1.7 on 2025-03-14 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "triggers",
            "0002_remove_trigger_api_payload_remove_trigger_interval_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="trigger",
            name="custom_frequency_expression",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("custom", "Custom"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
