# Generated by Django 5.1.7 on 2025-03-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("triggers", "0003_trigger_custom_frequency_expression_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trigger",
            name="creation_source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("api", "API")],
                default="manual",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="trigger",
            name="custom_frequency_expression",
            field=models.CharField(
                blank=True,
                help_text="Cron expression for custom frequency, e.g., '*/5 * * * *'",
                max_length=255,
                null=True,
            ),
        ),
    ]
