# Generated by Django 5.1.7 on 2025-03-15 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("triggers", "0004_trigger_creation_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trigger",
            name="creation_source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("api", "API")],
                default="manual",
                max_length=50,
            ),
        ),
    ]
