# Generated by Django 5.1.7 on 2025-03-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("triggers", "0005_alter_trigger_creation_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="trigger",
            name="payload",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
