# Generated by Django 5.1.7 on 2025-03-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("triggers", "0006_trigger_payload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trigger",
            name="frequency",
            field=models.CharField(
                blank=True,
                choices=[
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("monthly", "Monthly"),
                    ("custom", "Custom"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
