# Generated by Django 5.1.7 on 2025-03-13 16:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_logs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventlog",
            name="executed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
