# Generated by Django 5.1.7 on 2025-03-14 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_logs", "0002_eventlog_executed_at"),
        ("triggers", "0003_trigger_custom_frequency_expression_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventlog",
            name="trigger",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="triggers.trigger",
            ),
        ),
    ]
