# Generated by Django 5.1.7 on 2025-03-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_logs", "0003_alter_eventlog_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventlog",
            name="trigger_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="eventlog",
            name="trigger_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
