# Generated by Django 5.1.7 on 2025-03-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event_logs", "0004_eventlog_trigger_name_eventlog_trigger_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventlog",
            name="creation_source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("api", "API")],
                default="manual",
                max_length=10,
            ),
        ),
    ]
